name: Test and Lint

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test-and-lint:
    name: Test and Lint
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install infokup package
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[dev]

      - name: Lint
        run: ruff check

      - name: Test
        run: python -m tests.test_infokup
