name: Test and Lint

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  natjecanje-iz-informatike:
    name: Natjecanje iz informatike
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Lint with Ruff
        uses: chartboost/ruff-action@v1
          
      - name: Test
        run: python test.py
